-- 0006_legacy_tam.sql
-- GENERATED by tools/gen_legacy_ddl.py from the legacy database schema - DO NOT EDIT BY HAND.
--   verify: .venv/bin/python tools/gen_legacy_ddl.py --check      (a file that is not applied yet may be refreshed with --write --allow-change)
--
-- Source database : legacy/companyOps/tam/data/tam.sqlite3   (opened read-only / immutable; never modified)
-- Purpose         : companyOps TAM build: 13 India sector categories, company universe, classification, ICP score, sourcing funnel events, CRM push log, Apollo cost ledger
-- Source schema   : 17 tables, 16 indexes, 0 views; sqlite_master sha256 = eff0a2328b8e975a56c5828fffa2be2bc4901c574114183753a787af066d47dd
-- Prefix          : legacy_tam_
--
-- VERBATIM IMPORT LAYER.  Nothing is dropped: every table keeps its original columns, types, defaults, CHECKs, UNIQUEs,
-- primary keys (incl. AUTOINCREMENT) and foreign keys (retargeted to the prefixed parents).  Each table gets one extra
-- column _import_run_id (-> ops_import_run), indexed (ix_<table>_run), so an import can be traced and reversed (DELETE ... WHERE _import_run_id = ?).
-- Tables are NOT STRICT on purpose (legacy data is loosely typed); canonical tables are.  The declared foreign keys are kept, so
-- importers must load parents before children; legacy rows that already violate their own foreign keys must be loaded anyway (with
-- PRAGMA foreign_keys = OFF, set outside a transaction), listed by PRAGMA foreign_key_check and reported to ops_dq_issue
-- (rule_code 'legacy_fk_orphan'), never dropped.  ON DELETE actions are kept exactly as in the source: nothing under leadgen/ deletes from legacy_*.
-- Canonical rows link back to these rows through origin_ref(source_system, source_table, source_pk); source_table is the ORIGINAL name
-- (not the prefixed one) and tables without a primary key (see the table list) use their rowid as source_pk - copy rowid explicitly on load.

-- table async_jobs -> legacy_tam_async_jobs
CREATE TABLE legacy_tam_async_jobs (
  id INTEGER PRIMARY KEY, vendor TEXT, request_id TEXT, payload TEXT,
  status TEXT DEFAULT 'pending', attempts INT DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now')), resolved_at TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table categories -> legacy_tam_categories
CREATE TABLE legacy_tam_categories (
  id INTEGER PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  status TEXT DEFAULT 'active',
  hubspot_segment TEXT,
  config_path TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table category_sources -> legacy_tam_category_sources
CREATE TABLE legacy_tam_category_sources (
  category_id INT NOT NULL REFERENCES legacy_tam_categories(id),
  source TEXT NOT NULL,
  tier TEXT,                    -- free | paid | manual_only
  status TEXT,                  -- ok | partial | blocked | manual_only | not_built | error
  access_method TEXT,           -- http | playwright | vendor_api | manual_export | tarball
  url TEXT,
  robots_status TEXT,           -- allowed | disallowed | not_checked
  blocked_reason TEXT,          -- WHY it failed/was not used, in plain words
  rows_total INT DEFAULT 0,
  rows_new_total INT DEFAULT 0,
  attempts INT DEFAULT 0,
  last_attempt_at TEXT,
  last_success_at TEXT,
  saturated INT DEFAULT 0,
  notes TEXT,
  updated_at TEXT DEFAULT (datetime('now')),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  PRIMARY KEY (category_id, source)
);

-- table classifications -> legacy_tam_classifications
CREATE TABLE legacy_tam_classifications (
  company_id INT NOT NULL REFERENCES legacy_tam_companies(id),
  category_id INT NOT NULL REFERENCES legacy_tam_categories(id),
  keyword_score REAL, keyword_hits TEXT,
  segments TEXT, primary_segment TEXT,
  icp_bucket TEXT CHECK (icp_bucket IN ('Fit','Maybe','Out')),
  confidence REAL, has_own_tech_product INT, india_hq TEXT, company_type TEXT,
  evidence_quote TEXT, evidence_url TEXT, pm_tooling_signals TEXT, notes TEXT,
  model TEXT, prompt_version TEXT,
  classified_at TEXT DEFAULT (datetime('now')),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  PRIMARY KEY (company_id, category_id)
);

-- table companies -> legacy_tam_companies
CREATE TABLE legacy_tam_companies (
  id INTEGER PRIMARY KEY,
  root_domain TEXT UNIQUE,
  linkedin_url TEXT,
  name TEXT NOT NULL,
  name_norm TEXT,
  alt_domains TEXT,
  hq_city TEXT, hq_state TEXT, hq_country TEXT,
  india_hq TEXT CHECK (india_hq IN ('yes','no','unknown')) DEFAULT 'unknown',
  employee_count INT, headcount_band TEXT, founded_year INT,
  funding_stage TEXT, total_funding_usd REAL,
  office_phone TEXT, google_place_id TEXT, apollo_org_id TEXT,
  site_status TEXT, final_url TEXT,
  first_seen_at TEXT DEFAULT (datetime('now')), last_seen_at TEXT
, legal_name TEXT, cin TEXT, domain_confidence REAL, merged_into INT REFERENCES legacy_tam_companies(id),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table company_categories -> legacy_tam_company_categories
CREATE TABLE legacy_tam_company_categories (
  company_id INT NOT NULL REFERENCES legacy_tam_companies(id),
  category_id INT NOT NULL REFERENCES legacy_tam_categories(id),
  segment TEXT,
  icp_bucket TEXT CHECK (icp_bucket IN ('Fit','Maybe','Out')),
  confidence REAL,
  score REAL,
  priority_tier TEXT,
  first_seen_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT, regulated_status TEXT, regulatory_sensitivity TEXT, parked_as TEXT, funnel_stage TEXT, funnel_bucket TEXT, funnel_reason TEXT, funnel_updated_at TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  PRIMARY KEY (company_id, category_id)
);

-- table contacts -> legacy_tam_contacts
CREATE TABLE legacy_tam_contacts (
  id INTEGER PRIMARY KEY,
  company_id INT REFERENCES legacy_tam_companies(id),
  apollo_person_id TEXT UNIQUE,
  full_name TEXT, first_name TEXT, last_name TEXT, title TEXT,
  seniority TEXT, role_rank INT, linkedin_url TEXT,
  email TEXT, email_status TEXT, email_verified_at TEXT,
  phone_mobile TEXT, phone_other TEXT, phone_source TEXT,
  in_salesnav INT DEFAULT 0, enrich_state TEXT DEFAULT 'found',
  created_at TEXT DEFAULT (datetime('now')), updated_at TEXT
, category_id INT, funnel_stage TEXT, funnel_bucket TEXT, funnel_reason TEXT, funnel_updated_at TEXT, email_bucket TEXT, phone_bucket TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table cost_ledger -> legacy_tam_cost_ledger
CREATE TABLE legacy_tam_cost_ledger (
  id INTEGER PRIMARY KEY, run_id INT, category_id INT REFERENCES legacy_tam_categories(id),
  vendor TEXT, unit TEXT, qty REAL, usd_est REAL, note TEXT,
  at TEXT DEFAULT (datetime('now')),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table crm_pushes -> legacy_tam_crm_pushes
CREATE TABLE legacy_tam_crm_pushes (
  id INTEGER PRIMARY KEY,
  company_id INT REFERENCES legacy_tam_companies(id),
  category_id INT REFERENCES legacy_tam_categories(id),
  crm TEXT DEFAULT 'hubspot',
  deal_id TEXT, contact_id TEXT, owner TEXT, pipeline TEXT, dealstage TEXT,
  segment TEXT, status TEXT DEFAULT 'pushed', note TEXT,
  pushed_at TEXT DEFAULT (datetime('now')),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table funnel_events -> legacy_tam_funnel_events
CREATE TABLE legacy_tam_funnel_events (
  id INTEGER PRIMARY KEY,
  category_id INT REFERENCES legacy_tam_categories(id),
  entity_type TEXT NOT NULL CHECK (entity_type IN ('company','contact')),
  entity_id INT NOT NULL,
  stage TEXT NOT NULL,
  bucket TEXT NOT NULL,
  reason TEXT,
  source TEXT,
  run_id INT REFERENCES legacy_tam_stage_runs(id),
  at TEXT DEFAULT (datetime('now')),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table outreach_batches -> legacy_tam_outreach_batches
CREATE TABLE legacy_tam_outreach_batches (
  id INTEGER PRIMARY KEY, batch_no INT, contact_id INT REFERENCES legacy_tam_contacts(id),
  channel TEXT, created_at TEXT DEFAULT (datetime('now')),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table pages -> legacy_tam_pages
CREATE TABLE legacy_tam_pages (
             id INTEGER PRIMARY KEY,
             company_id INT REFERENCES legacy_tam_companies(id),
             url TEXT, page_type TEXT, title TEXT, text TEXT, markdown TEXT,
             http_status INT, text_hash TEXT,
             crawled_at TEXT DEFAULT (datetime('now')),
             _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  UNIQUE(company_id, url)
           );

-- table raw_sources -> legacy_tam_raw_sources
CREATE TABLE legacy_tam_raw_sources (
  id INTEGER PRIMARY KEY,
  category_id INT REFERENCES legacy_tam_categories(id),
  source TEXT NOT NULL, source_ref TEXT,
  run_id INT REFERENCES legacy_tam_stage_runs(id),
  company_name TEXT, website TEXT, root_domain TEXT, linkedin_url TEXT,
  city TEXT, state TEXT, country TEXT, phone TEXT,
  segment_hint TEXT, signal_text TEXT, payload_json TEXT,
  fetched_at TEXT DEFAULT (datetime('now')),
  company_id INT REFERENCES legacy_tam_companies(id),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  UNIQUE(source, source_ref, company_name, website)
);

-- table salesnav_import -> legacy_tam_salesnav_import
CREATE TABLE legacy_tam_salesnav_import (
  id INTEGER PRIMARY KEY, file TEXT, company_name TEXT, company_linkedin_url TEXT,
  website TEXT, root_domain TEXT, person_name TEXT, person_title TEXT,
  person_linkedin_url TEXT, imported_at TEXT DEFAULT (datetime('now')),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table signalhire_results -> legacy_tam_signalhire_results
CREATE TABLE legacy_tam_signalhire_results (
  item TEXT PRIMARY KEY,          -- the LinkedIn URL we submitted
  status TEXT,
  mobile TEXT,
  email TEXT,
  raw TEXT,
  received_at TEXT DEFAULT (datetime('now')),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table signals -> legacy_tam_signals
CREATE TABLE legacy_tam_signals (
  company_id INT PRIMARY KEY REFERENCES legacy_tam_companies(id),
  mx_provider TEXT, mx_records TEXT, techs TEXT,
  uses_jira INT, uses_slack INT, uses_asana INT, uses_clickup INT, uses_gworkspace INT,
  jira_scrum_mentions INT, open_jobs INT,
  updated_at TEXT DEFAULT (datetime('now')),
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table stage_runs -> legacy_tam_stage_runs
CREATE TABLE legacy_tam_stage_runs (
  id INTEGER PRIMARY KEY,
  category_id INT REFERENCES legacy_tam_categories(id),
  stage TEXT, source TEXT, args TEXT,
  started_at TEXT DEFAULT (datetime('now')), finished_at TEXT, status TEXT,
  rows_in INT, rows_new INT, rows_seen INT, saturated INT DEFAULT 0, error TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

CREATE INDEX legacy_tam_ix_cc_cat ON legacy_tam_company_categories(category_id, icp_bucket);
CREATE INDEX legacy_tam_ix_cc_funnel ON legacy_tam_company_categories(category_id, funnel_stage, funnel_bucket);
CREATE INDEX legacy_tam_ix_co_legal ON legacy_tam_companies(legal_name);
CREATE INDEX legacy_tam_ix_co_li ON legacy_tam_companies(linkedin_url);
CREATE INDEX legacy_tam_ix_co_merged ON legacy_tam_companies(merged_into);
CREATE INDEX legacy_tam_ix_co_name ON legacy_tam_companies(name_norm);
CREATE INDEX legacy_tam_ix_co_namenorm_nodom ON legacy_tam_companies(name_norm) WHERE root_domain IS NULL;
CREATE INDEX legacy_tam_ix_crm_company ON legacy_tam_crm_pushes(company_id);
CREATE INDEX legacy_tam_ix_ct_funnel ON legacy_tam_contacts(category_id, funnel_stage, funnel_bucket);
CREATE INDEX legacy_tam_ix_fe_cat ON legacy_tam_funnel_events(category_id, stage, bucket);
CREATE INDEX legacy_tam_ix_fe_entity ON legacy_tam_funnel_events(entity_type, entity_id, stage);
CREATE INDEX legacy_tam_ix_pages_company ON legacy_tam_pages(company_id);
CREATE INDEX legacy_tam_ix_pages_url ON legacy_tam_pages(url);
CREATE INDEX legacy_tam_ix_rs_domain ON legacy_tam_raw_sources(root_domain);
CREATE UNIQUE INDEX legacy_tam_ux_crm_deal ON legacy_tam_crm_pushes(crm, deal_id) WHERE deal_id IS NOT NULL;
CREATE UNIQUE INDEX legacy_tam_ux_ct_li ON legacy_tam_contacts(linkedin_url) WHERE linkedin_url IS NOT NULL;

-- _import_run_id indexes (import tracing / reversal / FK maintenance on ops_import_run)
CREATE INDEX ix_legacy_tam_async_jobs_run ON legacy_tam_async_jobs(_import_run_id);
CREATE INDEX ix_legacy_tam_categories_run ON legacy_tam_categories(_import_run_id);
CREATE INDEX ix_legacy_tam_category_sources_run ON legacy_tam_category_sources(_import_run_id);
CREATE INDEX ix_legacy_tam_classifications_run ON legacy_tam_classifications(_import_run_id);
CREATE INDEX ix_legacy_tam_companies_run ON legacy_tam_companies(_import_run_id);
CREATE INDEX ix_legacy_tam_company_categories_run ON legacy_tam_company_categories(_import_run_id);
CREATE INDEX ix_legacy_tam_contacts_run ON legacy_tam_contacts(_import_run_id);
CREATE INDEX ix_legacy_tam_cost_ledger_run ON legacy_tam_cost_ledger(_import_run_id);
CREATE INDEX ix_legacy_tam_crm_pushes_run ON legacy_tam_crm_pushes(_import_run_id);
CREATE INDEX ix_legacy_tam_funnel_events_run ON legacy_tam_funnel_events(_import_run_id);
CREATE INDEX ix_legacy_tam_outreach_batches_run ON legacy_tam_outreach_batches(_import_run_id);
CREATE INDEX ix_legacy_tam_pages_run ON legacy_tam_pages(_import_run_id);
CREATE INDEX ix_legacy_tam_raw_sources_run ON legacy_tam_raw_sources(_import_run_id);
CREATE INDEX ix_legacy_tam_salesnav_import_run ON legacy_tam_salesnav_import(_import_run_id);
CREATE INDEX ix_legacy_tam_signalhire_results_run ON legacy_tam_signalhire_results(_import_run_id);
CREATE INDEX ix_legacy_tam_signals_run ON legacy_tam_signals(_import_run_id);
CREATE INDEX ix_legacy_tam_stage_runs_run ON legacy_tam_stage_runs(_import_run_id);
