-- 0007_legacy_itsvc.sql
-- GENERATED by tools/gen_legacy_ddl.py from the legacy database schema - DO NOT EDIT BY HAND.
--   verify: .venv/bin/python tools/gen_legacy_ddl.py --check      (a file that is not applied yet may be refreshed with --write --allow-change)
--
-- Source database : legacy/hubspot/itsvc-tam/itsvc.db   (opened read-only / immutable; never modified)
-- Purpose         : India IT-services universe from Apollo org search (candidates -> entities, classifications incl. placeholder priors, raw record index, site text)
-- Source schema   : 12 tables, 6 indexes, 0 views; sqlite_master sha256 = 0a6d2fe1e4db43070de0978956de43066163d15fcb071059697f6477bffbf4d3
-- Prefix          : legacy_itsvc_
--
-- VERBATIM IMPORT LAYER.  Nothing is dropped: every table keeps its original columns, types, defaults, CHECKs, UNIQUEs,
-- primary keys (incl. AUTOINCREMENT) and foreign keys (retargeted to the prefixed parents).  Each table gets one extra
-- column _import_run_id (-> ops_import_run), indexed (ix_<table>_run), so an import can be traced and reversed (DELETE ... WHERE _import_run_id = ?).
-- Tables are NOT STRICT on purpose (legacy data is loosely typed); canonical tables are.  The declared foreign keys are kept, so
-- importers must load parents before children; legacy rows that already violate their own foreign keys must be loaded anyway (with
-- PRAGMA foreign_keys = OFF, set outside a transaction), listed by PRAGMA foreign_key_check and reported to ops_dq_issue
-- (rule_code 'legacy_fk_orphan'), never dropped.  ON DELETE actions are kept exactly as in the source: nothing under leadgen/ deletes from legacy_*.
-- Canonical rows link back to these rows through origin_ref(source_system, source_table, source_pk); source_table is the ORIGINAL name
-- (not the prefixed one) and tables without a primary key (see the table list) use their rowid as source_pk - copy rowid explicitly on load.

-- table candidates -> legacy_itsvc_candidates
CREATE TABLE legacy_itsvc_candidates(
    id INTEGER PRIMARY KEY,
    raw_id INTEGER REFERENCES legacy_itsvc_raw_records(id),
    source TEXT NOT NULL,
    name TEXT,
    legal_name TEXT,
    cin TEXT,
    llpin TEXT,
    gstin TEXT,
    pan TEXT,
    domain TEXT,
    website TEXT,
    linkedin_url TEXT,
    phone_e164 TEXT,
    email_generic TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    pincode TEXT,
    lat REAL,
    lng REAL,
    headcount_raw TEXT,
    headcount_band TEXT,
    nic_code TEXT,
    company_class TEXT,
    paid_up_capital_inr REAL,
    incorporation_date TEXT,
    mca_status TEXT,
    mca_subcategory TEXT,
    description TEXT,
    types_json TEXT,
    partner_program TEXT,
    partner_tier TEXT,
    extra_json TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table captures -> legacy_itsvc_captures
CREATE TABLE legacy_itsvc_captures(
    entity_id TEXT REFERENCES legacy_itsvc_entities(entity_id),
    source TEXT,
    stratum_key TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table cities -> legacy_itsvc_cities
CREATE TABLE legacy_itsvc_cities(
    city TEXT PRIMARY KEY,
    state TEXT,
    tier INTEGER,
    bbox_json TEXT,
    aliases_json TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table classifications -> legacy_itsvc_classifications
CREATE TABLE legacy_itsvc_classifications(
    entity_id TEXT REFERENCES legacy_itsvc_entities(entity_id),
    model TEXT,
    prompt_version TEXT,
    builds_software INTEGER,
    dev_intensity INTEGER,
    subsegments_json TEXT,
    tags_json TEXT,
    exclusion_flags_json TEXT,
    tech_stack_json TEXT,
    erp_platforms_json TEXT,
    export_focus INTEGER,
    evidence_json TEXT,
    confidence REAL,
    rules_applied_json TEXT,
    cost_usd REAL,
    created_at TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table cost_ledger -> legacy_itsvc_cost_ledger
CREATE TABLE legacy_itsvc_cost_ledger(
    id INTEGER PRIMARY KEY,
    provider TEXT NOT NULL,
    units REAL,
    usd REAL NOT NULL,
    ts TEXT NOT NULL,
    task_key TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table entities -> legacy_itsvc_entities
CREATE TABLE legacy_itsvc_entities(
    entity_id TEXT PRIMARY KEY,
    canonical_name TEXT,
    legal_name TEXT,
    cin TEXT,
    llpin TEXT,
    domain TEXT,
    linkedin_url TEXT,
    city TEXT,
    state TEXT,
    city_tier INTEGER,
    headcount_band TEXT,
    first_seen TEXT,
    last_seen TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table entity_members -> legacy_itsvc_entity_members
CREATE TABLE legacy_itsvc_entity_members(
    entity_id TEXT REFERENCES legacy_itsvc_entities(entity_id),
    candidate_id INTEGER REFERENCES legacy_itsvc_candidates(id),
    rule_id TEXT,
    score REAL,
    _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  PRIMARY KEY (entity_id, candidate_id)
);

-- table er_decisions -> legacy_itsvc_er_decisions
CREATE TABLE legacy_itsvc_er_decisions(
    id INTEGER PRIMARY KEY,
    a_candidate INTEGER,
    b_candidate INTEGER,
    rule_id TEXT,
    score REAL,
    decision TEXT,
    ts TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table partner_badges -> legacy_itsvc_partner_badges
CREATE TABLE legacy_itsvc_partner_badges(
    entity_id TEXT REFERENCES legacy_itsvc_entities(entity_id),
    program TEXT,
    tier TEXT,
    url TEXT,
    fetched_at TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table raw_records -> legacy_itsvc_raw_records
CREATE TABLE legacy_itsvc_raw_records(
    id INTEGER PRIMARY KEY,
    source TEXT NOT NULL,
    source_url TEXT,
    fetched_at TEXT NOT NULL,
    raw_sha256 TEXT NOT NULL,
    payload_path TEXT,
    task_key TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table site_text -> legacy_itsvc_site_text
CREATE TABLE legacy_itsvc_site_text(
    entity_id TEXT PRIMARY KEY,
    domain TEXT,
    status TEXT,
    http_code INTEGER,
    text TEXT,
    cin TEXT,
    email_generic TEXT,
    fetched_at TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table suppression -> legacy_itsvc_suppression
CREATE TABLE legacy_itsvc_suppression(
    id INTEGER PRIMARY KEY,
    entity_id TEXT,
    domain TEXT,
    email TEXT,
    phone_e164 TEXT,
    reason TEXT,
    ts TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

CREATE INDEX legacy_itsvc_idx_candidates_cin ON legacy_itsvc_candidates(cin);
CREATE INDEX legacy_itsvc_idx_candidates_city ON legacy_itsvc_candidates(city);
CREATE INDEX legacy_itsvc_idx_candidates_domain ON legacy_itsvc_candidates(domain);
CREATE INDEX legacy_itsvc_idx_candidates_phone ON legacy_itsvc_candidates(phone_e164);
CREATE INDEX legacy_itsvc_idx_captures_entity ON legacy_itsvc_captures(entity_id);
CREATE INDEX legacy_itsvc_idx_entities_domain ON legacy_itsvc_entities(domain);

-- _import_run_id indexes (import tracing / reversal / FK maintenance on ops_import_run)
CREATE INDEX ix_legacy_itsvc_candidates_run ON legacy_itsvc_candidates(_import_run_id);
CREATE INDEX ix_legacy_itsvc_captures_run ON legacy_itsvc_captures(_import_run_id);
CREATE INDEX ix_legacy_itsvc_cities_run ON legacy_itsvc_cities(_import_run_id);
CREATE INDEX ix_legacy_itsvc_classifications_run ON legacy_itsvc_classifications(_import_run_id);
CREATE INDEX ix_legacy_itsvc_cost_ledger_run ON legacy_itsvc_cost_ledger(_import_run_id);
CREATE INDEX ix_legacy_itsvc_entities_run ON legacy_itsvc_entities(_import_run_id);
CREATE INDEX ix_legacy_itsvc_entity_members_run ON legacy_itsvc_entity_members(_import_run_id);
CREATE INDEX ix_legacy_itsvc_er_decisions_run ON legacy_itsvc_er_decisions(_import_run_id);
CREATE INDEX ix_legacy_itsvc_partner_badges_run ON legacy_itsvc_partner_badges(_import_run_id);
CREATE INDEX ix_legacy_itsvc_raw_records_run ON legacy_itsvc_raw_records(_import_run_id);
CREATE INDEX ix_legacy_itsvc_site_text_run ON legacy_itsvc_site_text(_import_run_id);
CREATE INDEX ix_legacy_itsvc_suppression_run ON legacy_itsvc_suppression(_import_run_id);
