-- 0008_legacy_corpus.sql
-- GENERATED by tools/gen_legacy_ddl.py from the legacy database schema - DO NOT EDIT BY HAND.
--   verify: .venv/bin/python tools/gen_legacy_ddl.py --check      (a file that is not applied yet may be refreshed with --write --allow-change)
--
-- Source database : legacy/hubspot/TAMBuildSpecs/_corpus/data/tam_corpus.sqlite   (opened read-only / immutable; never modified)
-- Purpose         : Generic multi-vertical corpus (uk_proptech, india_cobol_ip): companies, identifiers, EAV indicators, ICP score + components, source registry / health
-- Source schema   : 19 tables, 9 indexes, 3 views; sqlite_master sha256 = e4cee7f081ad0169d07c1314571e33b5f814005e201eafa864ee61425d94d3de
-- Prefix          : legacy_corpus_
--
-- VERBATIM IMPORT LAYER.  Nothing is dropped: every table keeps its original columns, types, defaults, CHECKs, UNIQUEs,
-- primary keys (incl. AUTOINCREMENT) and foreign keys (retargeted to the prefixed parents).  Each table gets one extra
-- column _import_run_id (-> ops_import_run), indexed (ix_<table>_run), so an import can be traced and reversed (DELETE ... WHERE _import_run_id = ?).
-- Tables are NOT STRICT on purpose (legacy data is loosely typed); canonical tables are.  The declared foreign keys are kept, so
-- importers must load parents before children; legacy rows that already violate their own foreign keys must be loaded anyway (with
-- PRAGMA foreign_keys = OFF, set outside a transaction), listed by PRAGMA foreign_key_check and reported to ops_dq_issue
-- (rule_code 'legacy_fk_orphan'), never dropped.  ON DELETE actions are kept exactly as in the source: nothing under leadgen/ deletes from legacy_*.
-- Canonical rows link back to these rows through origin_ref(source_system, source_table, source_pk); source_table is the ORIGINAL name
-- (not the prefixed one) and tables without a primary key (see the table list) use their rowid as source_pk - copy rowid explicitly on load.

-- table budget_ledger -> legacy_corpus_budget_ledger
CREATE TABLE legacy_corpus_budget_ledger (
  id          INTEGER PRIMARY KEY,
  provider    TEXT NOT NULL,
  vertical_id INTEGER REFERENCES legacy_corpus_vertical(id),
  units       TEXT,
  qty         REAL,
  cost_usd    REAL,
  stage       TEXT,
  run_id      TEXT,
  created_at  TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table company -> legacy_corpus_company
CREATE TABLE legacy_corpus_company (
  id              INTEGER PRIMARY KEY,
  vertical_id     INTEGER REFERENCES legacy_corpus_vertical(id),
  display_name    TEXT NOT NULL,
  legal_name      TEXT,
  name_norm       TEXT NOT NULL,           -- normalised for dedupe
  root_domain     TEXT,                    -- tldextract registered domain
  website         TEXT,
  linkedin_url    TEXT,
  country_code    TEXT,
  region          TEXT,                    -- sub-national: 'London', 'Karnataka'
  postcode        TEXT,
  headcount_est   INTEGER,
  headcount_band  TEXT,                    -- '51-200' -- band survives when exact is unknown
  headcount_source TEXT,
  founded_year    INTEGER,
  status          TEXT,                    -- active | dissolved | administration | liquidation | unknown
  status_detail   TEXT,
  status_as_of    TEXT,
  first_seen_at   TEXT NOT NULL,
  last_updated_at TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table company_identifier -> legacy_corpus_company_identifier
CREATE TABLE legacy_corpus_company_identifier (
  id          INTEGER PRIMARY KEY,
  company_id  INTEGER NOT NULL REFERENCES legacy_corpus_company(id) ON DELETE CASCADE,
  id_type     TEXT NOT NULL,               -- companies_house | cin | duns | domain | linkedin | vat | app_developer
  id_value    TEXT NOT NULL,
  is_primary  INTEGER DEFAULT 0,
  source_id   INTEGER REFERENCES legacy_corpus_source(id),
  confidence  REAL DEFAULT 1.0,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  UNIQUE(id_type, id_value, company_id)
);

-- table company_link -> legacy_corpus_company_link
CREATE TABLE legacy_corpus_company_link (
  id            INTEGER PRIMARY KEY,
  company_id    INTEGER NOT NULL REFERENCES legacy_corpus_company(id) ON DELETE CASCADE,
  link_type     TEXT NOT NULL,             -- parent_of | subsidiary_of | acquired_by | merged_into
                                           -- | trading_name | formerly_known_as | brand_of
  target_name   TEXT,
  target_company_id INTEGER REFERENCES legacy_corpus_company(id),
  target_ref    TEXT,                      -- external id when not in our DB
  effective_date TEXT,
  source_id     INTEGER REFERENCES legacy_corpus_source(id),
  confidence    REAL,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  UNIQUE(company_id, link_type, target_name)
);

-- table company_source -> legacy_corpus_company_source
CREATE TABLE legacy_corpus_company_source (
  company_id    INTEGER NOT NULL REFERENCES legacy_corpus_company(id) ON DELETE CASCADE,
  source_id     INTEGER NOT NULL REFERENCES legacy_corpus_source(id),
  attempt_id    INTEGER REFERENCES legacy_corpus_source_attempt(id),
  first_seen_at TEXT NOT NULL,
  source_ref    TEXT,                      -- id/url within that source
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  PRIMARY KEY(company_id, source_id)
);

-- table contact -> legacy_corpus_contact
CREATE TABLE legacy_corpus_contact (
  id              INTEGER PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES legacy_corpus_company(id) ON DELETE CASCADE,
  full_name       TEXT,
  title           TEXT,
  title_bucket    TEXT,
  seniority_rank  INTEGER,
  linkedin_url    TEXT,
  work_email      TEXT,
  email_status    TEXT,
  phone_e164      TEXT,
  phone_type      TEXT,                    -- mobile | direct | switchboard
  phone_source    TEXT,
  subscriber_type TEXT,                    -- corporate | individual | unknown  (PECR-style)
  dnc_checked     INTEGER DEFAULT 0,       -- generic do-not-call (TPS/CTPS/DNC/NDNC)
  dnc_registered  INTEGER,
  dnc_checked_at  TEXT,
  dnc_provider_ref TEXT,
  opted_out       INTEGER DEFAULT 0,
  legal_basis_ref TEXT,                    -- LIA reference / consent record
  source_id       INTEGER REFERENCES legacy_corpus_source(id),
  obtained_at     TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  UNIQUE(company_id, full_name)
);

-- table icp_rule -> legacy_corpus_icp_rule
CREATE TABLE legacy_corpus_icp_rule (
  id            INTEGER PRIMARY KEY,
  vertical_id   INTEGER NOT NULL REFERENCES legacy_corpus_vertical(id),
  slug          TEXT NOT NULL,
  display_name  TEXT,
  rule_kind     TEXT,                      -- indicator | keyword | firmographic | segment | penalty
  indicator_slug TEXT,                     -- when rule_kind='indicator'
  expression    TEXT,                      -- human-readable condition, e.g. 'headcount 50-200'
  weight        REAL NOT NULL,             -- may be negative (penalty) -- still never disqualifies
  max_points    REAL,                      -- cap for grouped rules
  group_name    TEXT,                      -- rules sharing a cap
  active        INTEGER DEFAULT 1,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  UNIQUE(vertical_id, slug)
);

-- table icp_score -> legacy_corpus_icp_score
CREATE TABLE legacy_corpus_icp_score (
  id              INTEGER PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES legacy_corpus_company(id) ON DELETE CASCADE,
  vertical_id     INTEGER NOT NULL REFERENCES legacy_corpus_vertical(id),
  score           REAL NOT NULL,           -- 0..100
  score_raw       REAL,                    -- before clamp/multiplier
  band            TEXT,                    -- P1 | P2 | P3 | P4  (descriptive only)
  match_label     TEXT,                    -- Fit | Maybe | Unclear  -- NO 'Out'; unclear stays in
  confidence      REAL,
  segments        TEXT,                    -- JSON array of icp_segment slugs
  scored_by       TEXT,                    -- 'rules_v1' | 'claude-haiku-4-5' | 'hybrid'
  model_id        TEXT,
  prompt_version  TEXT,
  rationale       TEXT,
  scored_at       TEXT NOT NULL,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  UNIQUE(company_id, vertical_id, scored_by)
);

-- table icp_score_component -> legacy_corpus_icp_score_component
CREATE TABLE legacy_corpus_icp_score_component (
  id            INTEGER PRIMARY KEY,
  icp_score_id  INTEGER NOT NULL REFERENCES legacy_corpus_icp_score(id) ON DELETE CASCADE,
  rule_id       INTEGER REFERENCES legacy_corpus_icp_rule(id),
  rule_slug     TEXT,
  points        REAL NOT NULL,
  detail        TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table icp_segment -> legacy_corpus_icp_segment
CREATE TABLE legacy_corpus_icp_segment (
  id            INTEGER PRIMARY KEY,
  vertical_id   INTEGER NOT NULL REFERENCES legacy_corpus_vertical(id),
  slug          TEXT NOT NULL,             -- 'marketplace', 'block_fm_saas'
  display_name  TEXT NOT NULL,
  description   TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  UNIQUE(vertical_id, slug)
);

-- table indicator -> legacy_corpus_indicator
CREATE TABLE legacy_corpus_indicator (
  id              INTEGER PRIMARY KEY,
  company_id      INTEGER NOT NULL REFERENCES legacy_corpus_company(id) ON DELETE CASCADE,
  indicator_id    INTEGER NOT NULL REFERENCES legacy_corpus_indicator_def(id),
  value_bool      INTEGER,
  value_num       REAL,
  value_text      TEXT,
  confidence      REAL DEFAULT 1.0,
  evidence_snippet TEXT,                   -- <=200 chars quoted from source
  evidence_url    TEXT,
  source_id       INTEGER REFERENCES legacy_corpus_source(id),
  raw_document_id INTEGER REFERENCES legacy_corpus_raw_document(id),
  observed_at     TEXT NOT NULL,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  UNIQUE(company_id, indicator_id, source_id)
);

-- table indicator_def -> legacy_corpus_indicator_def
CREATE TABLE legacy_corpus_indicator_def (
  id            INTEGER PRIMARY KEY,
  slug          TEXT NOT NULL UNIQUE,      -- 'has_work_orders', 'uses_jira', 'listings_volume'
  display_name  TEXT NOT NULL,
  category      TEXT,                      -- ops_exhaust | technographic | scale | credibility
                                           -- | distress | negative | segment | compliance | firmographic
  value_type    TEXT NOT NULL,             -- bool | int | float | text | enum | json
  enum_values   TEXT,                      -- JSON array when value_type='enum'
  polarity      TEXT DEFAULT 'positive',   -- positive | negative | neutral
                                           -- negative indicators REDUCE score; they never disqualify
  description   TEXT,
  vertical_id   INTEGER REFERENCES legacy_corpus_vertical(id),  -- NULL = shared across all verticals
  created_at    TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table raw_document -> legacy_corpus_raw_document
CREATE TABLE legacy_corpus_raw_document (
  id            INTEGER PRIMARY KEY,
  source_id     INTEGER NOT NULL REFERENCES legacy_corpus_source(id),
  attempt_id    INTEGER REFERENCES legacy_corpus_source_attempt(id),
  url           TEXT,
  content_hash  TEXT,
  payload_path  TEXT,                      -- data/raw/<source>/<hash>.json|html|csv
  fetched_at    TEXT NOT NULL,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  UNIQUE(source_id, content_hash)
);

-- table source -> legacy_corpus_source
CREATE TABLE legacy_corpus_source (
  id              INTEGER PRIMARY KEY,
  slug            TEXT NOT NULL UNIQUE,    -- 'ch_bulk', 'ukpa_directory', 'apify_website_crawler'
  display_name    TEXT NOT NULL,
  kind            TEXT,                    -- registry | directory | api | crawl | marketplace | manual_csv | search | stream
  base_url        TEXT,
  country_scope   TEXT,                    -- 'GB', 'IN', 'GLOBAL'
  auth_required   INTEGER DEFAULT 0,
  auth_env_key    TEXT,                    -- e.g. 'CH_API_KEY' -- lets us report "blocked: no key"
  is_paid         INTEGER DEFAULT 0,
  cost_model      TEXT,                    -- 'free', '$0.01/profile', '1 credit/call'
  licence_note    TEXT,                    -- 'OGL v3', 'ToS: manual import only'
  robots_policy   TEXT,                    -- allowed | disallowed | unknown | n/a
  tos_scrapable   INTEGER,                 -- 1 ok / 0 forbidden (manual CSV only) / NULL unknown
  reliability     TEXT,                    -- good | flaky | blocked | dead
  notes           TEXT,
  first_used_at   TEXT,
  last_used_at    TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table source_attempt -> legacy_corpus_source_attempt
CREATE TABLE legacy_corpus_source_attempt (
  id            INTEGER PRIMARY KEY,
  source_id     INTEGER NOT NULL REFERENCES legacy_corpus_source(id),
  vertical_id   INTEGER REFERENCES legacy_corpus_vertical(id),
  url           TEXT,
  method        TEXT,                      -- GET | POST | download | csv | api
  attempted_at  TEXT NOT NULL,
  http_status   INTEGER,
  outcome       TEXT NOT NULL,             -- ok | blocked_403 | rate_limited_429 | auth_required_401
                                           -- | robots_disallowed | tos_forbidden | paywalled
                                           -- | captcha | timeout | dns_fail | server_error | empty | parse_fail
  blocked_reason TEXT,                     -- free text: 'Cloudflare challenge', 'no CH_API_KEY in .env'
  bytes         INTEGER,
  rows_yielded  INTEGER,                   -- how many accounts this attempt actually produced
  elapsed_ms    INTEGER,
  run_id        TEXT,
  notes         TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table stage_run -> legacy_corpus_stage_run
CREATE TABLE legacy_corpus_stage_run (
  id          INTEGER PRIMARY KEY,
  run_id      TEXT,
  vertical_id INTEGER REFERENCES legacy_corpus_vertical(id),
  stage       TEXT NOT NULL,
  mode        TEXT,                        -- dry | sample | full
  input_hash  TEXT,
  cursor      TEXT,                        -- resumability checkpoint
  status      TEXT,                        -- running | ok | failed | halted_budget
  rows_in     INTEGER,
  rows_out    INTEGER,
  cost_usd    REAL,
  started_at  TEXT,
  finished_at TEXT,
  notes       TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table suppression -> legacy_corpus_suppression
CREATE TABLE legacy_corpus_suppression (
  id        INTEGER PRIMARY KEY,
  kind      TEXT NOT NULL,                 -- email | domain | phone | company_id | identifier
  value     TEXT NOT NULL UNIQUE,
  reason    TEXT,
  added_at  TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table verify_item -> legacy_corpus_verify_item
CREATE TABLE legacy_corpus_verify_item (
  id           INTEGER PRIMARY KEY,
  vertical_id  INTEGER REFERENCES legacy_corpus_vertical(id),
  ref          TEXT,                       -- 'V1'
  item         TEXT NOT NULL,
  status       TEXT DEFAULT 'pending',     -- pending | confirmed | changed | failed | blocked
  evidence_url TEXT,
  finding      TEXT,
  checked_at   TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  UNIQUE(vertical_id, ref)
);

-- table vertical -> legacy_corpus_vertical
CREATE TABLE legacy_corpus_vertical (
  id            INTEGER PRIMARY KEY,
  slug          TEXT NOT NULL UNIQUE,      -- 'uk_proptech'
  display_name  TEXT NOT NULL,             -- 'UK Real Estate / PropTech'
  region        TEXT,                      -- 'UK', 'IN', 'SG'
  country_code  TEXT,                      -- ISO-2, 'GB'
  spec_path     TEXT,                      -- path to the build-brief .md
  config_path   TEXT,                      -- path to vertical.yaml
  status        TEXT DEFAULT 'active',     -- active | paused | archived
  created_at    TEXT NOT NULL,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

CREATE INDEX legacy_corpus_ix_company_domain ON legacy_corpus_company(root_domain);
CREATE INDEX legacy_corpus_ix_company_status ON legacy_corpus_company(status);
CREATE INDEX legacy_corpus_ix_component_score ON legacy_corpus_icp_score_component(icp_score_id);
CREATE INDEX legacy_corpus_ix_icp_score_band ON legacy_corpus_icp_score(vertical_id, band);
CREATE INDEX legacy_corpus_ix_icp_score_score ON legacy_corpus_icp_score(vertical_id, score DESC);
CREATE INDEX legacy_corpus_ix_ident_lookup ON legacy_corpus_company_identifier(id_type, id_value);
CREATE INDEX legacy_corpus_ix_indicator_company ON legacy_corpus_indicator(company_id);
CREATE INDEX legacy_corpus_ix_indicator_def ON legacy_corpus_indicator(indicator_id);
CREATE UNIQUE INDEX legacy_corpus_ux_company_vert_norm ON legacy_corpus_company(vertical_id, name_norm);

-- _import_run_id indexes (import tracing / reversal / FK maintenance on ops_import_run)
CREATE INDEX ix_legacy_corpus_budget_ledger_run ON legacy_corpus_budget_ledger(_import_run_id);
CREATE INDEX ix_legacy_corpus_company_run ON legacy_corpus_company(_import_run_id);
CREATE INDEX ix_legacy_corpus_company_identifier_run ON legacy_corpus_company_identifier(_import_run_id);
CREATE INDEX ix_legacy_corpus_company_link_run ON legacy_corpus_company_link(_import_run_id);
CREATE INDEX ix_legacy_corpus_company_source_run ON legacy_corpus_company_source(_import_run_id);
CREATE INDEX ix_legacy_corpus_contact_run ON legacy_corpus_contact(_import_run_id);
CREATE INDEX ix_legacy_corpus_icp_rule_run ON legacy_corpus_icp_rule(_import_run_id);
CREATE INDEX ix_legacy_corpus_icp_score_run ON legacy_corpus_icp_score(_import_run_id);
CREATE INDEX ix_legacy_corpus_icp_score_component_run ON legacy_corpus_icp_score_component(_import_run_id);
CREATE INDEX ix_legacy_corpus_icp_segment_run ON legacy_corpus_icp_segment(_import_run_id);
CREATE INDEX ix_legacy_corpus_indicator_run ON legacy_corpus_indicator(_import_run_id);
CREATE INDEX ix_legacy_corpus_indicator_def_run ON legacy_corpus_indicator_def(_import_run_id);
CREATE INDEX ix_legacy_corpus_raw_document_run ON legacy_corpus_raw_document(_import_run_id);
CREATE INDEX ix_legacy_corpus_source_run ON legacy_corpus_source(_import_run_id);
CREATE INDEX ix_legacy_corpus_source_attempt_run ON legacy_corpus_source_attempt(_import_run_id);
CREATE INDEX ix_legacy_corpus_stage_run_run ON legacy_corpus_stage_run(_import_run_id);
CREATE INDEX ix_legacy_corpus_suppression_run ON legacy_corpus_suppression(_import_run_id);
CREATE INDEX ix_legacy_corpus_verify_item_run ON legacy_corpus_verify_item(_import_run_id);
CREATE INDEX ix_legacy_corpus_vertical_run ON legacy_corpus_vertical(_import_run_id);

-- view v_accounts -> legacy_corpus_v_accounts
CREATE VIEW legacy_corpus_v_accounts AS
SELECT c.id, v.slug AS vertical, c.display_name, c.root_domain, c.country_code,
       c.region, c.headcount_est, c.headcount_band, c.status,
       sc.score, sc.band, sc.match_label, sc.segments, sc.scored_by,
       (SELECT COUNT(*) FROM legacy_corpus_indicator i WHERE i.company_id=c.id)     AS indicator_count,
       (SELECT COUNT(*) FROM legacy_corpus_company_source cs WHERE cs.company_id=c.id) AS source_count
FROM legacy_corpus_company c
JOIN legacy_corpus_vertical v ON v.id=c.vertical_id
LEFT JOIN legacy_corpus_icp_score sc ON sc.company_id=c.id AND sc.vertical_id=c.vertical_id;

-- view v_corpus_summary -> legacy_corpus_v_corpus_summary
CREATE VIEW legacy_corpus_v_corpus_summary AS
SELECT v.slug AS vertical,
       COUNT(DISTINCT c.id)                                   AS companies,
       COUNT(DISTINCT CASE WHEN c.root_domain IS NOT NULL THEN c.id END) AS with_domain,
       COUNT(DISTINCT sc.id)                                  AS scored,
       SUM(sc.band='P1') AS p1, SUM(sc.band='P2') AS p2,
       SUM(sc.band='P3') AS p3, SUM(sc.band='P4') AS p4,
       ROUND(AVG(sc.score),1)                                 AS avg_score
FROM legacy_corpus_vertical v
LEFT JOIN legacy_corpus_company c ON c.vertical_id=v.id
LEFT JOIN legacy_corpus_icp_score sc ON sc.company_id=c.id
GROUP BY v.id;

-- view v_source_health -> legacy_corpus_v_source_health
CREATE VIEW legacy_corpus_v_source_health AS
SELECT s.slug, s.display_name, s.kind, s.is_paid, s.auth_env_key,
       COUNT(a.id)                                            AS attempts,
       SUM(a.outcome='ok')                                    AS ok,
       SUM(a.outcome<>'ok')                                   AS failures,
       SUM(a.outcome IN ('blocked_403','robots_disallowed','tos_forbidden',
                         'captcha','paywalled','auth_required_401'))  AS blocked,
       SUM(COALESCE(a.rows_yielded,0))                        AS rows_yielded,
       MAX(a.attempted_at)                                    AS last_attempt,
       GROUP_CONCAT(DISTINCT CASE WHEN a.outcome<>'ok' THEN a.outcome END) AS failure_modes
FROM legacy_corpus_source s LEFT JOIN legacy_corpus_source_attempt a ON a.source_id=s.id
GROUP BY s.id;
