-- 0009_legacy_pipeline.sql
-- GENERATED by tools/gen_legacy_ddl.py from the legacy database schema - DO NOT EDIT BY HAND.
--   verify: .venv/bin/python tools/gen_legacy_ddl.py --check      (a file that is not applied yet may be refreshed with --write --allow-change)
--
-- Source database : legacy/hubspot/lh2-pipeline/data/pipeline.sqlite   (opened read-only / immutable; never modified)
-- Purpose         : July 2026 GoodFirms / IT-services scrape: raw listings, companies + gate, people, SignalHire quota, API cache
-- Source schema   : 7 tables, 7 indexes, 0 views; sqlite_master sha256 = 869a1b0d8ffd03d05dcab724c056777dab212d484e12991a05f5a057c52ace64
-- Prefix          : legacy_pipeline_
--
-- VERBATIM IMPORT LAYER.  Nothing is dropped: every table keeps its original columns, types, defaults, CHECKs, UNIQUEs,
-- primary keys (incl. AUTOINCREMENT) and foreign keys (retargeted to the prefixed parents).  Each table gets one extra
-- column _import_run_id (-> ops_import_run), indexed (ix_<table>_run), so an import can be traced and reversed (DELETE ... WHERE _import_run_id = ?).
-- Tables are NOT STRICT on purpose (legacy data is loosely typed); canonical tables are.  The declared foreign keys are kept, so
-- importers must load parents before children; legacy rows that already violate their own foreign keys must be loaded anyway (with
-- PRAGMA foreign_keys = OFF, set outside a transaction), listed by PRAGMA foreign_key_check and reported to ops_dq_issue
-- (rule_code 'legacy_fk_orphan'), never dropped.  ON DELETE actions are kept exactly as in the source: nothing under leadgen/ deletes from legacy_*.
-- Canonical rows link back to these rows through origin_ref(source_system, source_table, source_pk); source_table is the ORIGINAL name
-- (not the prefixed one) and tables without a primary key (see the table list) use their rowid as source_pk - copy rowid explicitly on load.

-- table cache -> legacy_pipeline_cache
CREATE TABLE legacy_pipeline_cache (
    key        TEXT PRIMARY KEY,
    value_json TEXT,
    created_at TEXT NOT NULL,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table companies -> legacy_pipeline_companies
CREATE TABLE legacy_pipeline_companies (
    domain         TEXT PRIMARY KEY,
    company_name   TEXT,
    website        TEXT,
    city           TEXT,
    state          TEXT,
    hq_country     TEXT,
    founded_year   INTEGER,
    founded_source TEXT,
    size_band      TEXT,
    size_source    TEXT,
    size_bucket    TEXT,
    segment        TEXT,
    status         TEXT,
    sources_json   TEXT,
    gate_pass      INTEGER NOT NULL DEFAULT 0,
    gate_reason    TEXT,
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table crm_feedback -> legacy_pipeline_crm_feedback
CREATE TABLE legacy_pipeline_crm_feedback (
    email        TEXT PRIMARY KEY,
    domain       TEXT,
    call_outcome TEXT,
    call_notes   TEXT,
    call_date    TEXT,
    next_step    TEXT,
    pulled_at    TEXT NOT NULL,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table no_domain -> legacy_pipeline_no_domain
CREATE TABLE legacy_pipeline_no_domain (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    company_name TEXT,
    city         TEXT,
    source       TEXT,
    source_url   TEXT,
    created_at   TEXT NOT NULL,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table people -> legacy_pipeline_people
CREATE TABLE legacy_pipeline_people (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    domain             TEXT NOT NULL REFERENCES legacy_pipeline_companies(domain),
    name               TEXT,
    role               TEXT,
    name_source        TEXT,
    linkedin_url       TEXT,
    linkedin_source    TEXT,
    linkedin_confirmed INTEGER NOT NULL DEFAULT 0,
    phone              TEXT,
    phone_source       TEXT,
    email              TEXT,
    email_source       TEXT,
    is_primary         INTEGER NOT NULL DEFAULT 0,
    confidence         TEXT,
    notes              TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table quota -> legacy_pipeline_quota
CREATE TABLE legacy_pipeline_quota (
    provider    TEXT NOT NULL,
    metric      TEXT NOT NULL,          -- e.g. "requests" | "search" | "credits"
    window_key  TEXT NOT NULL,
    used        INTEGER NOT NULL DEFAULT 0,
    limit_value INTEGER,
    updated_at  TEXT NOT NULL,
    _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  PRIMARY KEY (provider, metric, window_key)
);

-- table raw_listings -> legacy_pipeline_raw_listings
CREATE TABLE legacy_pipeline_raw_listings (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    source           TEXT NOT NULL,
    source_url       TEXT NOT NULL,
    scraped_at       TEXT NOT NULL,
    company_name     TEXT,
    website_raw      TEXT,
    city             TEXT,
    founded_year_raw TEXT,
    size_raw         TEXT,
    segment_raw      TEXT,
    extra_json       TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

CREATE INDEX legacy_pipeline_ix_companies_gate ON legacy_pipeline_companies(gate_pass);
CREATE INDEX legacy_pipeline_ix_feedback_domain ON legacy_pipeline_crm_feedback(domain);
CREATE INDEX legacy_pipeline_ix_people_domain ON legacy_pipeline_people(domain);
CREATE INDEX legacy_pipeline_ix_raw_city        ON legacy_pipeline_raw_listings(city);
CREATE INDEX legacy_pipeline_ix_raw_source      ON legacy_pipeline_raw_listings(source);
CREATE UNIQUE INDEX legacy_pipeline_ux_people_domain_name ON legacy_pipeline_people(domain, name);
CREATE UNIQUE INDEX legacy_pipeline_ux_raw_src_url ON legacy_pipeline_raw_listings(source, source_url, company_name);

-- _import_run_id indexes (import tracing / reversal / FK maintenance on ops_import_run)
CREATE INDEX ix_legacy_pipeline_cache_run ON legacy_pipeline_cache(_import_run_id);
CREATE INDEX ix_legacy_pipeline_companies_run ON legacy_pipeline_companies(_import_run_id);
CREATE INDEX ix_legacy_pipeline_crm_feedback_run ON legacy_pipeline_crm_feedback(_import_run_id);
CREATE INDEX ix_legacy_pipeline_no_domain_run ON legacy_pipeline_no_domain(_import_run_id);
CREATE INDEX ix_legacy_pipeline_people_run ON legacy_pipeline_people(_import_run_id);
CREATE INDEX ix_legacy_pipeline_quota_run ON legacy_pipeline_quota(_import_run_id);
CREATE INDEX ix_legacy_pipeline_raw_listings_run ON legacy_pipeline_raw_listings(_import_run_id);
