-- 0011_legacy_radar.sql
-- GENERATED by tools/gen_legacy_ddl.py from the legacy database schema - DO NOT EDIT BY HAND.
--   verify: .venv/bin/python tools/gen_legacy_ddl.py --check      (a file that is not applied yet may be refreshed with --write --allow-change)
--
-- Source database : legacy/hubspot/godown/shutdown-radar/data/radar.sqlite   (opened read-only / immutable; never modified)
-- Purpose         : Indian startup shutdown radar: candidates, CIN entities, evidence, scoring, liveness, prequal
-- Source schema   : 10 tables, 4 indexes, 0 views; sqlite_master sha256 = 3945bc3b2c900e236a102e6a7df47767944e752cb2b3aff1d9b36f351df57092
-- Prefix          : legacy_radar_
--
-- VERBATIM IMPORT LAYER.  Nothing is dropped: every table keeps its original columns, types, defaults, CHECKs, UNIQUEs,
-- primary keys (incl. AUTOINCREMENT) and foreign keys (retargeted to the prefixed parents).  Each table gets one extra
-- column _import_run_id (-> ops_import_run), indexed (ix_<table>_run), so an import can be traced and reversed (DELETE ... WHERE _import_run_id = ?).
-- Tables are NOT STRICT on purpose (legacy data is loosely typed); canonical tables are.  The declared foreign keys are kept, so
-- importers must load parents before children; legacy rows that already violate their own foreign keys must be loaded anyway (with
-- PRAGMA foreign_keys = OFF, set outside a transaction), listed by PRAGMA foreign_key_check and reported to ops_dq_issue
-- (rule_code 'legacy_fk_orphan'), never dropped.  ON DELETE actions are kept exactly as in the source: nothing under leadgen/ deletes from legacy_*.
-- Canonical rows link back to these rows through origin_ref(source_system, source_table, source_pk); source_table is the ORIGINAL name
-- (not the prefixed one) and tables without a primary key (see the table list) use their rowid as source_pk - copy rowid explicitly on load.
--
-- LOAD NOTE: candidate_entity has 2 rows whose cin has no entity row (rowid 10783 and 10785; both match_method='override', is_confirmed=1 - human decisions):
-- LOAD NOTE: a verbatim load under foreign_keys=ON fails at COMMIT.  Load with foreign_keys=OFF and record both in ops_dq_issue(rule_code='legacy_fk_orphan').

-- table backfill_progress -> legacy_radar_backfill_progress
CREATE TABLE legacy_radar_backfill_progress (
  state_code TEXT PRIMARY KEY, last_offset INTEGER NOT NULL DEFAULT 0,
  total INTEGER, done INTEGER NOT NULL DEFAULT 0, updated_at TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table candidate -> legacy_radar_candidate
CREATE TABLE legacy_radar_candidate (
  id INTEGER PRIMARY KEY,
  brand_name TEXT NOT NULL,
  brand_name_norm TEXT NOT NULL UNIQUE,
  first_seen_at TEXT NOT NULL,
  discovery_source TEXT NOT NULL,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table candidate_entity -> legacy_radar_candidate_entity
CREATE TABLE legacy_radar_candidate_entity (
  candidate_id INTEGER NOT NULL REFERENCES legacy_radar_candidate(id),
  cin TEXT NOT NULL REFERENCES legacy_radar_entity(cin),
  match_score REAL NOT NULL,
  match_method TEXT NOT NULL,
  is_confirmed INTEGER NOT NULL DEFAULT 0,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id),
  PRIMARY KEY(candidate_id, cin)
);

-- table dpiit_startup -> legacy_radar_dpiit_startup
CREATE TABLE legacy_radar_dpiit_startup (
  id INTEGER PRIMARY KEY, name TEXT NOT NULL, name_norm TEXT NOT NULL,
  state TEXT, sector TEXT, recognition_date TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table entity -> legacy_radar_entity
CREATE TABLE legacy_radar_entity (
  cin TEXT PRIMARY KEY,
  legal_name TEXT NOT NULL, legal_name_norm TEXT NOT NULL,
  company_status TEXT, company_class TEXT, date_of_registration TEXT,
  registered_state TEXT, roc TEXT,
  source TEXT, fetched_at TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table evidence -> legacy_radar_evidence
CREATE TABLE legacy_radar_evidence (
  id INTEGER PRIMARY KEY,
  candidate_id INTEGER NOT NULL REFERENCES legacy_radar_candidate(id),
  kind TEXT NOT NULL,
  source_url TEXT, source_name TEXT, published_at TEXT,
  as_of_date TEXT,
  snippet TEXT,
  matched_pattern TEXT, raw_json TEXT,
  fetched_at TEXT NOT NULL,
  dedupe_key TEXT NOT NULL UNIQUE,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table liveness -> legacy_radar_liveness
CREATE TABLE legacy_radar_liveness (
  candidate_id INTEGER PRIMARY KEY REFERENCES legacy_radar_candidate(id),
  domain TEXT, dns_resolves INTEGER, http_status INTEGER, http_final_url TEXT,
  ssl_expired INTEGER, rdap_status TEXT, wayback_last_capture TEXT,
  liveness_score REAL, checked_at TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table prequal -> legacy_radar_prequal
CREATE TABLE legacy_radar_prequal (
  candidate_id INTEGER PRIMARY KEY REFERENCES legacy_radar_candidate(id),
  prequal_total INTEGER NOT NULL, prequal_max_possible INTEGER NOT NULL,
  prequal_pct REAL, prequal_routing TEXT, prequal_note TEXT, prequal_unscored TEXT,
  pq_funding INTEGER, pq_years INTEGER, pq_eng_headcount INTEGER, pq_sector INTEGER,
  pq_code_location INTEGER, pq_legal_status INTEGER,
  github_org TEXT, github_url TEXT, scored_at TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table run_stat -> legacy_radar_run_stat
CREATE TABLE legacy_radar_run_stat (
  k TEXT PRIMARY KEY, v TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table scored -> legacy_radar_scored
CREATE TABLE legacy_radar_scored (
  candidate_id INTEGER PRIMARY KEY REFERENCES legacy_radar_candidate(id),
  confidence REAL NOT NULL, tier TEXT NOT NULL,
  shutdown_date TEXT, shutdown_year INTEGER, reason TEXT,
  sector TEXT, city TEXT, funding_usd TEXT, investors TEXT,
  rationale TEXT NOT NULL, scored_at TEXT NOT NULL,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

CREATE INDEX legacy_radar_ix_cand_norm ON legacy_radar_candidate(brand_name_norm);
CREATE INDEX legacy_radar_ix_dpiit_norm ON legacy_radar_dpiit_startup(name_norm);
CREATE INDEX legacy_radar_ix_entity_norm ON legacy_radar_entity(legal_name_norm);
CREATE INDEX legacy_radar_ix_ev_cand ON legacy_radar_evidence(candidate_id);

-- _import_run_id indexes (import tracing / reversal / FK maintenance on ops_import_run)
CREATE INDEX ix_legacy_radar_backfill_progress_run ON legacy_radar_backfill_progress(_import_run_id);
CREATE INDEX ix_legacy_radar_candidate_run ON legacy_radar_candidate(_import_run_id);
CREATE INDEX ix_legacy_radar_candidate_entity_run ON legacy_radar_candidate_entity(_import_run_id);
CREATE INDEX ix_legacy_radar_dpiit_startup_run ON legacy_radar_dpiit_startup(_import_run_id);
CREATE INDEX ix_legacy_radar_entity_run ON legacy_radar_entity(_import_run_id);
CREATE INDEX ix_legacy_radar_evidence_run ON legacy_radar_evidence(_import_run_id);
CREATE INDEX ix_legacy_radar_liveness_run ON legacy_radar_liveness(_import_run_id);
CREATE INDEX ix_legacy_radar_prequal_run ON legacy_radar_prequal(_import_run_id);
CREATE INDEX ix_legacy_radar_run_stat_run ON legacy_radar_run_stat(_import_run_id);
CREATE INDEX ix_legacy_radar_scored_run ON legacy_radar_scored(_import_run_id);
