-- 0013_legacy_searchledger.sql
-- GENERATED by tools/gen_legacy_ddl.py from the legacy database schema - DO NOT EDIT BY HAND.
--   verify: .venv/bin/python tools/gen_legacy_ddl.py --check      (a file that is not applied yet may be refreshed with --write --allow-change)
--
-- Source database : legacy/hubspot/godown/founder_id/search_ledger.db   (opened read-only / immutable; never modified)
-- Purpose         : Ledger of LinkedIn-search API calls (quota / cost accounting) and events
-- Source schema   : 2 tables, 1 indexes, 0 views; sqlite_master sha256 = a8b77d99341e52063e5a77e5fd8a8d3d02f21af69dfc577da4305992270140a1
-- Prefix          : legacy_searchledger_
--
-- VERBATIM IMPORT LAYER.  Nothing is dropped: every table keeps its original columns, types, defaults, CHECKs, UNIQUEs,
-- primary keys (incl. AUTOINCREMENT) and foreign keys (retargeted to the prefixed parents).  Each table gets one extra
-- column _import_run_id (-> ops_import_run), indexed (ix_<table>_run), so an import can be traced and reversed (DELETE ... WHERE _import_run_id = ?).
-- Tables are NOT STRICT on purpose (legacy data is loosely typed); canonical tables are.  The declared foreign keys are kept, so
-- importers must load parents before children; legacy rows that already violate their own foreign keys must be loaded anyway (with
-- PRAGMA foreign_keys = OFF, set outside a transaction), listed by PRAGMA foreign_key_check and reported to ops_dq_issue
-- (rule_code 'legacy_fk_orphan'), never dropped.  ON DELETE actions are kept exactly as in the source: nothing under leadgen/ deletes from legacy_*.
-- Canonical rows link back to these rows through origin_ref(source_system, source_table, source_pk); source_table is the ORIGINAL name
-- (not the prefixed one) and tables without a primary key (see the table list) use their rowid as source_pk - copy rowid explicitly on load.

-- table calls -> legacy_searchledger_calls
CREATE TABLE legacy_searchledger_calls(
        id INTEGER PRIMARY KEY AUTOINCREMENT, ts_utc REAL, company TEXT, http_status INTEGER,
        profiles_returned INTEGER, size_used INTEGER, total_reported INTEGER, run_id TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table events -> legacy_searchledger_events
CREATE TABLE legacy_searchledger_events(ts_utc REAL, kind TEXT, note TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

CREATE INDEX legacy_searchledger_ix_calls_ts ON legacy_searchledger_calls(ts_utc);

-- _import_run_id indexes (import tracing / reversal / FK maintenance on ops_import_run)
CREATE INDEX ix_legacy_searchledger_calls_run ON legacy_searchledger_calls(_import_run_id);
CREATE INDEX ix_legacy_searchledger_events_run ON legacy_searchledger_events(_import_run_id);
