-- 0014_legacy_itdirs.sql
-- GENERATED by tools/gen_legacy_ddl.py from the legacy database schema - DO NOT EDIT BY HAND.
--   verify: .venv/bin/python tools/gen_legacy_ddl.py --check      (a file that is not applied yet may be refreshed with --write --allow-change)
--
-- Source database : legacy/hubspot/godown/itdirs/state/scrape_state.sqlite   (opened read-only / immutable; never modified)
-- Purpose         : IT-directory scraper resume state (regenerable; kept so nothing is dropped)
-- Source schema   : 3 tables, 0 indexes, 0 views; sqlite_master sha256 = 1222d7d692d18906552c343a871fbfd6bc60646702424346f65c0a7c35cdfb8b
-- Prefix          : legacy_itdirs_
--
-- VERBATIM IMPORT LAYER.  Nothing is dropped: every table keeps its original columns, types, defaults, CHECKs, UNIQUEs,
-- primary keys (incl. AUTOINCREMENT) and foreign keys (retargeted to the prefixed parents).  Each table gets one extra
-- column _import_run_id (-> ops_import_run), indexed (ix_<table>_run), so an import can be traced and reversed (DELETE ... WHERE _import_run_id = ?).
-- Tables are NOT STRICT on purpose (legacy data is loosely typed); canonical tables are.  The declared foreign keys are kept, so
-- importers must load parents before children; legacy rows that already violate their own foreign keys must be loaded anyway (with
-- PRAGMA foreign_keys = OFF, set outside a transaction), listed by PRAGMA foreign_key_check and reported to ops_dq_issue
-- (rule_code 'legacy_fk_orphan'), never dropped.  ON DELETE actions are kept exactly as in the source: nothing under leadgen/ deletes from legacy_*.
-- Canonical rows link back to these rows through origin_ref(source_system, source_table, source_pk); source_table is the ORIGINAL name
-- (not the prefixed one) and tables without a primary key (see the table list) use their rowid as source_pk - copy rowid explicitly on load.

-- table counters -> legacy_itdirs_counters
CREATE TABLE legacy_itdirs_counters(source TEXT, k TEXT, v INT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table pages -> legacy_itdirs_pages
CREATE TABLE legacy_itdirs_pages(url TEXT PRIMARY KEY, ts INT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- table redirects -> legacy_itdirs_redirects
CREATE TABLE legacy_itdirs_redirects(tracker TEXT PRIMARY KEY, domain TEXT,
  _import_run_id INTEGER REFERENCES ops_import_run(import_run_id)
);

-- _import_run_id indexes (import tracing / reversal / FK maintenance on ops_import_run)
CREATE INDEX ix_legacy_itdirs_counters_run ON legacy_itdirs_counters(_import_run_id);
CREATE INDEX ix_legacy_itdirs_pages_run ON legacy_itdirs_pages(_import_run_id);
CREATE INDEX ix_legacy_itdirs_redirects_run ON legacy_itdirs_redirects(_import_run_id);
